project:
  type: website
  preview:
    port: 3000
    watch-inputs: true


website:
  title: "INTERLIS IDE"
  site-url: https://edigonzales.github.io/interlis-ide
  favicon: images/ililogo1024.png
  navbar:
    pinned: true
    logo: images/ililogo1024.png
    logo-alt: INTERLIS IDE logo
    search: false
    left:
      - text: "Start"
        href: erste_schritte.qmd
      - text: "Dokumentation"
        menu: 
          - text: "Erste Schritte"
            href: erste_schritte.qmd
          - text: "Modellieren"
            href: modellieren.qmd
          - text: "Diagramme und Dokumente"
            href: diagramme_dokumente.qmd   
          - text: "Referenz"
            href: referenz.qmd
    right:
      - text: "INTERLIS-Spezifikation"
        href: https://www.ech.ch/de/ech/ech-0031/2.1.0
      - text: "interlis.ch"
        href: https://interlis.ch
      - icon: github
        href: https://github.com/edigonzales/interlis-ide
        aria-label: GitHub
  page-footer:
    left: "Copyright 2025 - 2026, INTERLIS IDE contributors"

format:
  html:
    theme:
      - default
      - inter-theme.scss
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    link-external-newwindow: true
    mainfont: Inter
    grid:
      sidebar-width: 290px
      margin-width: 280px
      body-width: 1150px

editor: visual
